# SPDX-FileCopyrightText: 2021 Toucan Labs
#
# SPDX-License-Identifier: LicenseRef-Proprietary

semi: true
singleQuote: true
trailingComma: es5
arrowParens: always
printWidth: 100
overrides:
  - files: 'packages/frontend/**/*'
    options:
      printWidth: 80
  - files: 'packages/hardhat/contracts/**/*'
    options:
      printWidth: 80
  - files: '*.sh'
    options:
      parser: sh
      tabWidth: 4
  - files: packages/services/graph-node/bin/*
    options:
      parser: sh
      tabWidth: 4
